CREATE TABLE IF NOT EXISTS `find_jobs` (
  `id` bigint AUTO_INCREMENT PRIMARY KEY,
  `project_fk` bigint unsigned NOT NULL,
  `player` varchar(255) NOT NULL,
  `team` varchar(255) NOT NULL,
  `season` int NOT NULL,
  `opponent` varchar(255),
  `source_limit` int NOT NULL DEFAULT 20,
  `clip_limit` int NOT NULL DEFAULT 30,
  `preferred_height` int NOT NULL DEFAULT 1080,
  `minimum_height` int NOT NULL DEFAULT 720,
  `pre_roll_sec` double NOT NULL DEFAULT 10,
  `post_roll_sec` double NOT NULL DEFAULT 15,
  `local_asr_fallback` boolean NOT NULL DEFAULT true,
  `status` varchar(48) NOT NULL DEFAULT 'queued',
  `stage` varchar(80) NOT NULL DEFAULT 'queued',
  `current_operation` text,
  `pause_requested` boolean NOT NULL DEFAULT false,
  `cancel_requested` boolean NOT NULL DEFAULT false,
  `retry_count` int NOT NULL DEFAULT 0,
  `max_retries` int NOT NULL DEFAULT 3,
  `sources_found` int NOT NULL DEFAULT 0,
  `transcripts_found` int NOT NULL DEFAULT 0,
  `candidates_found` int NOT NULL DEFAULT 0,
  `clips_queued` int NOT NULL DEFAULT 0,
  `clips_verified` int NOT NULL DEFAULT 0,
  `warnings` text,
  `last_error` text,
  `last_progress_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `worker_heartbeat_at` timestamp NULL,
  `started_at` timestamp NULL,
  `completed_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `find_jobs_project_uq` (`project_fk`)
);

CREATE TABLE IF NOT EXISTS `find_sources` (
  `id` bigint AUTO_INCREMENT PRIMARY KEY,
  `job_fk` bigint unsigned NOT NULL,
  `project_fk` bigint unsigned NOT NULL,
  `video_id` varchar(32) NOT NULL,
  `video_fk` bigint unsigned,
  `url` text NOT NULL,
  `title` varchar(512),
  `channel` varchar(255),
  `duration_sec` int,
  `published_at` varchar(64),
  `search_query` varchar(512),
  `source_type` varchar(64) NOT NULL DEFAULT 'youtube',
  `rank_score` double NOT NULL DEFAULT 0,
  `caption_kind` varchar(32),
  `status` varchar(48) NOT NULL DEFAULT 'metadata',
  `attempt_count` int NOT NULL DEFAULT 0,
  `last_error` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `find_sources_job_video_uq` (`job_fk`, `video_id`)
);

ALTER TABLE `clip_jobs`
  ADD COLUMN IF NOT EXISTS `minimum_height` int NOT NULL DEFAULT 720 AFTER `height`;
