CREATE TABLE IF NOT EXISTS `clip_package_edit_versions` (
  `id` varchar(36) NOT NULL,
  `project_fk` bigint unsigned NOT NULL,
  `candidate_fk` bigint unsigned NOT NULL,
  `source_video_fk` bigint unsigned NOT NULL,
  `source_clip_job_fk` bigint unsigned NOT NULL,
  `studio_export_fk` bigint unsigned,
  `studio_draft_id` varchar(120),
  `intent` enum('new_version','replacement') NOT NULL DEFAULT 'new_version',
  `status` enum('draft','exporting','ready','failed','retired') NOT NULL DEFAULT 'draft',
  `active_replacement` boolean NOT NULL DEFAULT false,
  `original_in` double NOT NULL,
  `original_out` double NOT NULL,
  `edit_in` double NOT NULL,
  `edit_out` double NOT NULL,
  `drive_path` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `clip_package_edit_versions_project_candidate_idx` (`project_fk`, `candidate_fk`),
  KEY `clip_package_edit_versions_studio_export_idx` (`studio_export_fk`),
  KEY `clip_package_edit_versions_active_idx` (`project_fk`, `candidate_fk`, `active_replacement`)
);
